Repository MDAnalysis/MDAnalysis.github.io, pull requests merged in 2024-01, with the labels that each got.

#344 Create blog post about moving to GitHub Discussions
  _posts/2023-12-21-github-discussions.md
Labels: Blog

#342 update governance: PIs must be CoreDevs
  about.md
Labels: core pages

#339 Add funding information to website
  about.md
Labels: core pages

#346 Draft blog post for describing 2023 and announcing 2024 UGM/workshop
  _posts/2023-12-23-mda_events.md
  public/images/20231025_Online_Workshop.png
  public/images/UGM2023_Group_Photo.jpeg
  public/images/UGM2023_Hackathon.jpeg
Labels: Blog

#341 Final GSoC blog post and call for mentors
  _posts/2024-01-11-gsoc2023-final.md
  _posts/2024-01-11-gsoc2023_marinegor.md
  _posts/2024-01-11-gsoc2023_xhgchen.md
Labels: Blog, GSoC
