Repository MDAnalysis/MDAnalysis.github.io, pull requests merged in 2025-03, with the labels that each got.

#436 FIX broken links
  _posts/2024-05-27-gsoc-outreachy-students.md
  _posts/2024-08-30-gsoc2024-final-sm.md
  _posts/2025-02-11-gsoc2024-final-lg.md
  about.md
  index.md
  pages/installation_quick_start.md
  pages/learning_MDAnalysis.md
  pages/mdakits.md
Labels: SDG23

#432 Teams: Add Namir to documentation team
  _data/team/roles/documentation.yml
Labels: core pages

#429 Teams: Add Micaela and Yuxuan to external liaison team
  _data/team/roles/external_liaison.yml
Labels: core pages

#440 Sdg23 update installation quick start page
  pages/installation_quick_start.md
Labels: SDG23

#431 Teams: Clarify that sub-project managers are also responsible for maintenance
  _data/team/roles/core_library_maintenance.yml
Labels: core pages

#434 update to ruby >= 2.7, <4
  Gemfile
  INSTALL.md
  README.md
  _config.yml
Labels: build system

#427 Teams: Integrate 'social media' into 'community engagement' tasks
  _config.yml
  _data/team/roles/community_engagement.yml
  _data/team/roles/social_media.yml
Labels: core pages, configuration

#445 Sdg23 add documentation page
  pages/documentation.md
Labels: SDG23

#430 Teams: Rephrase task on helping with specific MDAKits
  _data/team/roles/mdakit_registry.yml
Labels: core pages

#444 Sdg23 refine 'learning MDAnalysis' page
  pages/learning_MDAnalysis.md
Labels: SDG23

#443 Sdg23 add getting started page md
  pages/basic_example.md
  pages/getting_started.md
  pages/installation_quick_start.md
  public/css/local.css
Labels: SDG23

#447 add community page
  pages/community.md
Labels: SDG23

#455 update landing page
  index.md
Labels: SDG23

#451 Refined About, Mission, Governance, and Funding pages
  about.md
  conduct.md
  mission.md
  pages/funding.md
  pages/governance.md
Labels: SDG23

#456 update citations page
  pages/citations.md
Labels: SDG23

#446 Sdg23 add contribute page
  _config.yml
  pages/contribute.md
Labels: SDG23

#450 Sdg23 add events page
  pages/events.md
  pages/ugm2024.md
Labels: SDG23

#442 Sdg23 restructure sidebar in website
  _config.yml
  _includes/head.html
  _includes/sidebar.html
  about.md
  blog/index.html
  pages/citations.md
  pages/privacy.md
  pages/team.md
  public/css/local.css
  public/images/bluesky.svg
Labels: SDG23

#428 Teams: Integrate 'teaching materials' into 'workshops and meetings' tasks
  _data/team/roles/outreach.yml
Labels: core pages
